### ISSUE TITLE
Errors in tests due timeouts in io events and counter

### ISSUE THREAD

**Issue by mauroglo89** [Rafailong/usergrid-counters#1]
Unstable performance testing increment/decrement counters by event due timeouts. 

When trying to retrieve counter after event creation and increment the counter, it retrieves a non existing counter `counters[0].values.length == 0`, an existing counter but not with the increment `counters[0].values[0].value = 0` or the incremented value `counters[0].values[0].value = 10`

```javascript
c = new UsergrindCounter.configureClient(opts) //Adds client credentials and app's data
c.createEvent('counterName') //Creates counter with default value 0 for 'counterName' event
/*
 It should wait until event is created,
between 20 and 30 seconds
*/
c.incrementCounter('counterName', 10) //Increments 'counterName' counter by 10
/*
Problem with async performance
*/
c.getCounter('counterName') 
```

**Comment by Rafailong** [comment]
@mauroglo89 can you be more explicit? It would be good to have a scenario.

Thanks!
