### ISSUE TITLE
Creating multiple events through createEvent doesnt work

### ISSUE THREAD

**Issue by mauroglo89** [Rafailong/usergrid-counters#2]
The service concats all the events as one string, so it only creates one event.
```javascript
createEvent(['event1',event2]) // returns eventName: 'event1,event2'
```

**Comment by Rafailong** [comment]
Solved with [nested counter](https://github.com/Rafailong/usergrid-counters/commit/3877623b5aadbd0194516f058263ac04065e3cb4)
